id: scripts
name: Scripts
description: Check scripts
metrics:
  external-scripts-count:
    id: external-scripts-count
    name: External scripts
    description: The number of external scripts
    order: 65
    aggregation: sum
  external-scripts-size:
    id: external-scripts-size
    name: External scripts size
    description: The total size of external scripts
    order: 65
    unit: byte
    aggregation: sum
  embedded-scripts-count:
    id: embedded-scripts-count
    name: Embedded scripts
    description: The number of embedded scripts
    order: 65
    aggregation: sum
  embedded-scripts-size:
    id: embedded-scripts-size
    name: Embedded scripts size
    description: The total size of embedded scripts
    order: 65
    unit: byte
    aggregation: sum
rules:
  externalise-script:
    id: externalise-script
    name: Externalise script
    description: Avoid embedding script into the HTML page
    references: [115bp#41]
  minify-script:
    id: minify-script
    name: Minify script
    description: Reduce the size of the script by minifying JS code
    references: [115bp#77]
  reduce-scripts-count:
    id: reduce-scripts-count
    name: Reduce scripts count
    description: Reduce the number of scripts
    references: [115bp#35, 115bp#75]
  reduce-script-size:
    id: reduce-script-size
    name: Reduce script size
    description: Reduce the size of the script
    references: [115bp#15, 115bp#77]
