id: fonts
name: Fonts
description: Check for fonts
metrics:
  external-fonts-count:
    id: external-fonts-count
    name: External fonts count
    description: The number of external fonts
    order: 50
    aggregation: sum
  external-fonts-size:
    id: external-fonts-size
    name: External fonts size
    description: The total size of external fonts
    order: 50
    unit: byte
    aggregation: sum
rules:
  use-standard-fonts:
    id: use-standard-fonts
    name: Use standard fonts
    description: Use fonts already pre-installed on user terminals
