name: main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NODE_VERSION: 18
  GIST_ID: fbde4d59b7dd3c4f2cc9c4fea3497ae1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - run: npm ci
      # - run: npm run lint
      - run: npm run build
      - run: npm pack
      - uses: actions/upload-artifact@v3
        with:
          name: ecojourney
          path: ecojourney-*.tgz

  test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.31.0-focal
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - run: npm ci
      - run: npm run test:all:coverage || true
      - uses: gaelgirodon/ci-badges-action@v1
        with:
          gist-id: ${{ env.GIST_ID }}
          token: ${{ secrets.GIST_TOKEN }}
      - uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            coverage/*coverage.xml
            test-results.xml
