id: embedded-assets
name: Embedded assets
description: Check for embedded styles and scripts
metrics:
  embedded-styles:
    id: embedded-styles
    name: Embedded styles
    description: The number of embedded styles
    order: 51
    aggregation: sum
  embedded-scripts:
    id: embedded-scripts
    name: Embedded scripts
    description: The number of embedded scripts
    order: 52
    aggregation: sum
rules:
  externalise-style:
    id: externalise-style
    name: Externalise style
    description: Externalise style
  externalise-script:
    id: externalise-script
    name: Externalise script
    description: Externalise script
references:
  - 115bp#41
